name: Clear caches

on:
  schedule:
    - cron: '0 0 1 * *'  # First day of the month >> Just clean all the caches
  workflow_dispatch:

jobs:
  clear-caches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Clear all caches
        run: gh cache delete --all || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
